### ISSUE TITLE
What was the reason for this?

### ISSUE THREAD

**Issue by donuts-are-good** [charmbracelet/keygen#7]
I'm curious what caused the thought "ssh-keygen, nah, I need my own thing". Was it a limitation of ssh-keygen, or just do to it?

**Comment by cloudybyte** [comment]
I'm not associated with charmbracelet, but I believe the difference is in this being a native go implementation, and ssh-keygen being a cli-based tool.
It probably has sth to do with performance and being able to fully test/cover the code.
